server.port: 8080

spring:
  kafka.consumer:
    bootstrap-servers: localhost:9092
    key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    group-id: notification
    properties.spring.json.trusted.packages: "*"

  mail:
    host: smtp.gmail.com
    port: 587
    username: user
    password: pass
    properties.mail:
      smtp.auth: true
      smtp.starttls.enable: true