server.port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: db
    password: db
    driver-class-name: org.postgresql.Driver

  kafka.producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  jpa:
    hibernate:
      ddl-auto: update